name: Rotate iOS Certs (Fastlane Match)
on:
  workflow_dispatch: {}   # îl rulezi manual

jobs:
  rotate:
    runs-on: macos-14
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      GH_PAT:         ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install fastlane
        run: gem install fastlane

      # construim fișierul API key din secretele tale existente
      - name: Create App Store Connect API key file
        run: |
          mkdir -p fastlane
          cat > fastlane/api_key.json <<'EOF'
          {
            "key_id":    "${{ secrets.FASTLANE_KEY_ID }}",
            "issuer_id": "${{ secrets.FASTLANE_ISSUER_ID }}",
            "key":       "${{ secrets.FASTLANE_KEY }}",
            "in_house":  false
          }
          EOF

      - name: Create NEW Distribution cert + App Store profiles
        run: |
          # dăm voie lui match să scrie în repo-ul Match
          export MATCH_GIT_BASIC_AUTHORIZATION=$(echo -n "${GITHUB_REPOSITORY_OWNER}:${GH_PAT}" | base64)

          # scoatem read-only + forțăm certificat nou
          fastlane match appstore \
            --readonly false \
            --generate_apple_certs true \
            --force_for_new_certificates true \
            --api_key_path fastlane/api_key.json \
            --verbose
